### ISSUE TITLE
does not work with current node-version anymore

### ISSUE THREAD

**Issue by juliusPeters** [automata/osc-web#15]
I an using osc-web for some time (thank you for your work). Since my last update (linux and node) it does not start anymore. This hasn't changed with the modifications ftom Dec. 7th.
 When trying to start it by "node bridge.js' node stops and displays these messages.

.../osc-web/node_modules/socket.io/lib/store.js:35
 Store.prototype.proto = EventEmitter.prototype;
 ^

TypeError: Cannot read property 'prototype' of undefined
 at Object. (.../osc-web/node_modules/socket.io/lib/store.js:35:42)
 at Module._compile (module.js:652:30)
 at Object.Module._extensions..js (module.js:663:10)
 at Module.load (module.js:565:32)
 at tryModuleLoad (module.js:505:12)
 at Function.Module._load (module.js:497:3)
 at Module.require (module.js:596:17)
 at require (internal/module.js:11:18)
 at Object. (.../osc-web/node_modules/socket.io/lib/manager.js:16:13)
 at Module._compile (module.js:652:30)

This seems to have something to do with deprecated functions of node. Do you have any idea?

Thanks
 Julius

**Comment by automata** [comment]
Sorry for the long hiatus Julius. I'm dusting off `osc-web` and just updated dependencies. Tested with latest  Node LTS (v12.13.0) and it works now.

Thanks you!
